import type { Metadata } from "next";
import { Inter } from "next/font/google";
import MuiTheme from "./theme/theme";
import Providers from "@/redux/providers";
import { getServerSession } from "next-auth";
import { AuthProvider } from "@/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "To-do App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider session={session}>
          <Providers>
            <MuiTheme>{children}</MuiTheme>
          </Providers>
        </AuthProvider>
      </body>
    </html>
  );
}
