import type { Metadata } from "next";
import { Inter } from "next/font/google";
import MuiTheme from "./theme/theme";
import Providers from "@/redux/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "To-do App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <MuiTheme>{children}</MuiTheme>
        </Providers>
      </body>
    </html>
  );
}
